name = "ZeroYBMS"
version = "0.1.0"
defaultTargets = ["ZeroY", "OneY"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "YesMetaZFC"
path = "../vendor/bms"

[[lean_lib]]
name = "ZeroY"

[[lean_lib]]
name = "OneY"
